import { Check, Clock3, MessageCircle, RefreshCw, Search, Trash2, UserPlus, X } from 'lucide-react';
import { type FormEvent, useEffect, useState } from 'react';
import { Header } from '../components/Header';
import { cancelContactRequest, loadContactRequests, loadNexusContacts, removeNexusContact, respondContactRequest, searchNexusUser, sendContactRequest, type NexusContact, type NexusContactRequest, type NexusUserSearchResult } from '../features/data/contactsData';

type ContactsPageProps = { onStartChat?: (contactUserId: string) => Promise<{ error: string | null }> };
function initials(name: string | null, username: string | null) { return (name || username || 'N').split(/\s+/).filter(Boolean).map((v) => v[0]).join('').slice(0, 2).toUpperCase(); }
function displayName(name: string | null, username: string | null) { return name || (username ? `@${username}` : 'Nexus Nutzer'); }

export function ContactsPage({ onStartChat }: ContactsPageProps) {
  const [contacts, setContacts] = useState<NexusContact[]>([]); const [requests, setRequests] = useState<NexusContactRequest[]>([]); const [query, setQuery] = useState(''); const [searchResult, setSearchResult] = useState<NexusUserSearchResult | null>(null); const [loading, setLoading] = useState(true); const [searching, setSearching] = useState(false); const [actionId, setActionId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [feedback, setFeedback] = useState<string | null>(null);
  const incoming = requests.filter((r) => r.direction === 'incoming'); const outgoing = requests.filter((r) => r.direction === 'outgoing');
  const refresh = async () => { setLoading(true); setError(null); const [a,b] = await Promise.all([loadNexusContacts(), loadContactRequests()]); setContacts(a.data); setRequests(b.data); setError(a.error || b.error || null); setLoading(false); };
  useEffect(() => { void refresh(); }, []);
  const runSearch = async (username = query) => { const normalized=username.trim(); if(!normalized)return; setSearching(true);setFeedback(null);setSearchResult(null);const r=await searchNexusUser(normalized);setSearching(false);if(r.error){setFeedback(r.error);return;}if(!r.data){setFeedback('Kein Nexus-Nutzer mit diesem Username gefunden.');return;}setSearchResult(r.data); };
  const submitSearch=(e:FormEvent)=>{e.preventDefault();void runSearch();};
  const requestContact=async(userId:string)=>{setActionId(userId);setFeedback(null);const r=await sendContactRequest(userId);setActionId(null);if(r.error){setFeedback(r.error);return;}setFeedback('Kontaktanfrage gesendet.');await refresh();await runSearch(query);};
  const answerRequest=async(id:string,accept:boolean)=>{setActionId(id);setFeedback(null);const r=await respondContactRequest(id,accept);setActionId(null);if(r.error){setFeedback(r.error);return;}setFeedback(accept?'Kontaktanfrage angenommen.':'Kontaktanfrage abgelehnt.');await refresh();if(query.trim())await runSearch(query);};
  const cancelRequest=async(id:string)=>{setActionId(id);const r=await cancelContactRequest(id);setActionId(null);if(r.error){setFeedback(r.error);return;}setFeedback('Kontaktanfrage zurückgezogen.');await refresh();};
  const removeContact=async(contact:NexusContact)=>{if(!window.confirm(`${displayName(contact.full_name,contact.username)} wirklich aus deinen Kontakten entfernen?`))return;setActionId(contact.contact_user_id);const r=await removeNexusContact(contact.contact_user_id);setActionId(null);if(r.error){setFeedback(r.error);return;}setFeedback('Kontakt entfernt.');await refresh();};
  const startChat=async(contact:NexusContact)=>{if(!onStartChat)return;setActionId(contact.contact_user_id);setFeedback(null);const r=await onStartChat(contact.contact_user_id);setActionId(null);if(r.error)setFeedback(r.error);};
  const relationshipLabel=(r:NexusUserSearchResult['relationship'])=>r==='contact'?'Bereits Kontakt':r==='incoming'?'Anfrage von dieser Person erhalten':r==='outgoing'?'Kontaktanfrage gesendet':null;

  return <section className="page contacts-page">
    <div className="title-row"><Header kicker="IDENTITÄT & NETZWERK" title="Kontakte" sub="Echte Nexus-Nutzer finden, Kontaktanfragen verwalten und dein Netzwerk aufbauen."/><button className="secondary contacts-refresh" onClick={()=>void refresh()} disabled={loading}><RefreshCw size={15}/>{loading?'Lädt…':'Aktualisieren'}</button></div>
    {error&&<div className="data-alert">Backend: {error}</div>}{feedback&&<div className="contact-feedback">{feedback}</div>}
    <div className="contact-search-panel panel"><div><Search size={20}/><div><h3>Nexus-Nutzer finden</h3><p>Suche aus Datenschutzgründen exakt nach dem Nexus-Username, z. B. <b>@darlynovic</b>.</p></div></div><form className="contact-search-form" onSubmit={submitSearch}><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="@username" autoComplete="off"/><button className="primary" disabled={searching||!query.trim()}><Search size={15}/>{searching?'Sucht…':'Suchen'}</button></form>
      {searchResult&&<div className="contact-search-result"><div className="avatar big">{initials(searchResult.full_name,searchResult.username)}</div><div className="contact-person-copy"><b>{displayName(searchResult.full_name,searchResult.username)}</b><span>{searchResult.username?`@${searchResult.username}`:'Kein Username'}</span>{relationshipLabel(searchResult.relationship)&&<small>{relationshipLabel(searchResult.relationship)}</small>}</div>{searchResult.relationship==='none'?<button className="primary" onClick={()=>void requestContact(searchResult.user_id)} disabled={actionId===searchResult.user_id}><UserPlus size={15}/>Anfrage senden</button>:<span className="contact-status-pill">{relationshipLabel(searchResult.relationship)}</span>}</div>}
    </div>
    <div className="contacts-summary"><div className="stat"><b>{contacts.length}</b><span>Kontakte</span></div><div className="stat"><b>{incoming.length}</b><span>Eingehende Anfragen</span></div><div className="stat"><b>{outgoing.length}</b><span>Gesendete Anfragen</span></div></div>
    {(incoming.length>0||outgoing.length>0)&&<div className="contact-requests-grid"><div className="panel"><h3>Eingehende Anfragen</h3>{incoming.length===0&&<p className="contact-empty">Keine offenen Anfragen.</p>}{incoming.map((r)=><div className="contact-request-row" key={r.request_id}><div className="avatar">{initials(r.full_name,r.username)}</div><div className="contact-person-copy"><b>{displayName(r.full_name,r.username)}</b><span>{r.username?`@${r.username}`:'Nexus Nutzer'}</span></div><div className="contact-request-actions"><button className="contact-icon-button accept" title="Annehmen" onClick={()=>void answerRequest(r.request_id,true)} disabled={actionId===r.request_id}><Check size={16}/></button><button className="contact-icon-button" title="Ablehnen" onClick={()=>void answerRequest(r.request_id,false)} disabled={actionId===r.request_id}><X size={16}/></button></div></div>)}</div><div className="panel"><h3>Gesendete Anfragen</h3>{outgoing.length===0&&<p className="contact-empty">Keine offenen Anfragen.</p>}{outgoing.map((r)=><div className="contact-request-row" key={r.request_id}><div className="avatar">{initials(r.full_name,r.username)}</div><div className="contact-person-copy"><b>{displayName(r.full_name,r.username)}</b><span>{r.username?`@${r.username}`:'Nexus Nutzer'}</span><small><Clock3 size={12}/> wartet auf Antwort</small></div><button className="contact-icon-button" title="Anfrage zurückziehen" onClick={()=>void cancelRequest(r.request_id)} disabled={actionId===r.request_id}><X size={16}/></button></div>)}</div></div>}
    <div className="contacts-section-heading"><div><h2>Meine Kontakte</h2><p>Starte jetzt direkt einen echten 1:1-Chat mit deinen Nexus-Kontakten.</p></div></div>
    {loading&&contacts.length===0?<div className="panel contact-empty-state">Kontakte werden geladen…</div>:contacts.length===0?<div className="panel contact-empty-state"><UserPlus size={28}/><b>Noch keine Nexus-Kontakte</b><span>Suche oben nach einem Username und sende deine erste Kontaktanfrage.</span></div>:<div className="contact-grid real-contacts">{contacts.map((c)=><div className="contact" key={c.contact_user_id}><div className="avatar big">{initials(c.full_name,c.username)}</div><b>{displayName(c.full_name,c.username)}</b><span>{c.username?`@${c.username}`:'Nexus Nutzer'}</span><small>Nexus-Kontakt</small><div className="contact-card-actions"><button onClick={()=>void startChat(c)} disabled={actionId===c.contact_user_id}><MessageCircle size={14}/>{actionId===c.contact_user_id?'Öffnet…':'Chat öffnen'}</button><button className="contact-remove" title="Kontakt entfernen" onClick={()=>void removeContact(c)} disabled={actionId===c.contact_user_id}><Trash2 size={14}/></button></div></div>)}</div>}
  </section>;
}