-- Isolated synthetic fixtures. Always rollback; binary objects are never changed with SQL.
BEGIN;
CREATE FUNCTION pg_temp.f(k text) RETURNS uuid LANGUAGE sql AS $$SELECT current_setting('nexus.files.'||k)::uuid;$$;
CREATE FUNCTION pg_temp.check_file(ok boolean,why text) RETURNS void LANGUAGE plpgsql AS $$BEGIN IF ok IS NOT TRUE THEN RAISE EXCEPTION '%',why; END IF;END$$;
CREATE FUNCTION pg_temp.file_login(k text) RETURNS void LANGUAGE sql AS $$SELECT set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.f(k),'role','authenticated','session_id',pg_temp.f(k||'_session'))::text,true);$$;
CREATE FUNCTION pg_temp.file_denied(statement text,expected text) RETURNS void LANGUAGE plpgsql AS $$
BEGIN BEGIN EXECUTE statement; EXCEPTION WHEN OTHERS THEN IF SQLSTATE=expected THEN RETURN; END IF; RAISE; END;
RAISE EXCEPTION 'Unexpectedly accepted: %',statement; END $$;
SELECT set_config('nexus.files.'||k,gen_random_uuid()::text,true) FROM unnest(ARRAY['owner','member','guest','outsider','owner_session','member_session','guest_session','outsider_session','workspace','foreign_ws','project','foreign_project','task','other_task','foreign_task','comment','other_comment','direct','comment_file','pending','expired','cascade']) k;
INSERT INTO auth.users(id,email,email_confirmed_at,raw_user_meta_data)
SELECT pg_temp.f(k),gen_random_uuid()||'@example.invalid',now(),'{"full_name":"Task file rollback acceptance"}' FROM unnest(ARRAY['owner','member','guest','outsider']) k;
INSERT INTO auth.sessions(id,user_id,created_at,updated_at)
SELECT pg_temp.f(k||'_session'),pg_temp.f(k),now(),now() FROM unnest(ARRAY['owner','member','guest','outsider']) k;
INSERT INTO public.workspaces(id,owner_id,name) VALUES(pg_temp.f('workspace'),pg_temp.f('owner'),'Files rollback workspace'),(pg_temp.f('foreign_ws'),pg_temp.f('outsider'),'Files foreign rollback');
INSERT INTO public.workspace_members(workspace_id,user_id,role) VALUES(pg_temp.f('workspace'),pg_temp.f('member'),'member'),(pg_temp.f('workspace'),pg_temp.f('guest'),'guest');
INSERT INTO public.projects(id,workspace_id,title) VALUES(pg_temp.f('project'),pg_temp.f('workspace'),'File project'),(pg_temp.f('foreign_project'),pg_temp.f('foreign_ws'),'Foreign project');
INSERT INTO public.project_tasks(id,workspace_id,project_id,title) VALUES(pg_temp.f('task'),pg_temp.f('workspace'),pg_temp.f('project'),'File task'),(pg_temp.f('other_task'),pg_temp.f('workspace'),pg_temp.f('project'),'Other file task'),(pg_temp.f('foreign_task'),pg_temp.f('foreign_ws'),pg_temp.f('foreign_project'),'Foreign file task');
SELECT pg_temp.file_login('member');
SET LOCAL ROLE authenticated;
INSERT INTO public.task_comments(id,workspace_id,task_id,body) VALUES(pg_temp.f('comment'),pg_temp.f('workspace'),pg_temp.f('task'),'Own comment');
SELECT public.begin_task_attachment(pg_temp.f('direct'),pg_temp.f('workspace'),pg_temp.f('task'),NULL,'Plan.pdf','application/pdf',10);
SELECT pg_temp.check_file(public.begin_task_attachment(pg_temp.f('direct'),pg_temp.f('workspace'),pg_temp.f('task'),NULL,'Plan.pdf','application/pdf',10)->>'id'=pg_temp.f('direct')::text,'Retry changed intent');
SELECT public.begin_task_attachment(pg_temp.f('comment_file'),pg_temp.f('workspace'),pg_temp.f('task'),pg_temp.f('comment'),'Bild.png','image/png',10);
SELECT pg_temp.check_file(private.task_file_access(pg_temp.f('workspace')||'/'||pg_temp.f('task')||'/'||pg_temp.f('member')||'/'||pg_temp.f('direct'),true),'Author cannot upload reserved file');
SELECT pg_temp.check_file(NOT EXISTS(SELECT 1 FROM public.task_attachments WHERE task_id=pg_temp.f('task')),'Pending file metadata exposed');
SELECT pg_temp.file_denied($q$SELECT public.finish_task_attachment(pg_temp.f('direct'))$q$,'P0001');
SELECT pg_temp.file_denied($q$SELECT public.begin_task_attachment(pg_temp.f('direct'),pg_temp.f('workspace'),pg_temp.f('task'),NULL,'Changed.pdf','application/pdf',10)$q$,'23514');
SELECT pg_temp.file_denied($q$SELECT public.begin_task_attachment(gen_random_uuid(),pg_temp.f('workspace'),pg_temp.f('foreign_task'),NULL,'x.pdf','application/pdf',10)$q$,'23503');
SELECT pg_temp.file_denied($q$SELECT public.begin_task_attachment(gen_random_uuid(),pg_temp.f('foreign_ws'),pg_temp.f('foreign_task'),NULL,'x.pdf','application/pdf',10)$q$,'42501');
SELECT pg_temp.file_denied($q$SELECT public.begin_task_attachment(gen_random_uuid(),pg_temp.f('workspace'),pg_temp.f('other_task'),pg_temp.f('comment'),'x.pdf','application/pdf',10)$q$,'42501');
DO $$ DECLARE file_name text; BEGIN
 FOREACH file_name IN ARRAY ARRAY['../Plan.pdf',E'x\\Plan.pdf',E'x\nPlan.pdf','Plan.svg','Plan.pdf '] LOOP
  PERFORM pg_temp.file_denied(format('SELECT public.begin_task_attachment(gen_random_uuid(),pg_temp.f(''workspace''),pg_temp.f(''task''),NULL,%L,''application/pdf'',10)',file_name),'23514');
 END LOOP;
END $$;
SELECT pg_temp.file_denied($q$SELECT public.begin_task_attachment(gen_random_uuid(),pg_temp.f('workspace'),pg_temp.f('task'),NULL,'Plan.pdf','text/html',10)$q$,'23514');
SELECT pg_temp.file_denied($q$SELECT public.begin_task_attachment(gen_random_uuid(),pg_temp.f('workspace'),pg_temp.f('task'),NULL,'Plan.pdf','application/pdf',26214401)$q$,'23514');
SELECT pg_temp.file_denied($q$UPDATE public.task_attachments SET state='ready' WHERE id=pg_temp.f('direct')$q$,'42501');
SELECT pg_temp.file_denied($q$DELETE FROM public.task_attachments WHERE id=pg_temp.f('direct')$q$,'42501');
SELECT pg_temp.file_denied($q$SELECT public.claim_task_file_cleanup()$q$,'42501');
SELECT pg_temp.file_denied($q$SELECT private.wake_task_file_cleanup(true)$q$,'42501');
RESET ROLE;
-- Ready metadata fixtures test RLS; actual Storage upload/finalization is tested through the API.
UPDATE public.task_attachments SET state='ready' WHERE task_id=pg_temp.f('task');
SELECT pg_temp.file_login('owner');
SET LOCAL ROLE authenticated;
INSERT INTO public.task_comments(id,workspace_id,task_id,body) VALUES(pg_temp.f('other_comment'),pg_temp.f('workspace'),pg_temp.f('task'),'Other author');
SELECT pg_temp.file_denied($q$SELECT public.begin_task_attachment(gen_random_uuid(),pg_temp.f('workspace'),pg_temp.f('task'),pg_temp.f('comment'),'x.pdf','application/pdf',10)$q$,'42501');
RESET ROLE;
SELECT pg_temp.file_login('guest');
SET LOCAL ROLE authenticated;
SELECT pg_temp.check_file((SELECT count(*)=2 FROM public.task_attachments WHERE task_id=pg_temp.f('task')),'Guest cannot read ready metadata');
SELECT pg_temp.check_file(private.task_file_access(pg_temp.f('workspace')||'/'||pg_temp.f('task')||'/'||pg_temp.f('member')||'/'||pg_temp.f('direct'),false),'Guest download denied');
SELECT pg_temp.check_file(NOT private.task_file_access(pg_temp.f('workspace')||'/'||pg_temp.f('task')||'/'||pg_temp.f('member')||'/'||pg_temp.f('direct'),true),'Guest upload allowed');
SELECT pg_temp.file_denied($q$SELECT public.begin_task_attachment(gen_random_uuid(),pg_temp.f('workspace'),pg_temp.f('task'),NULL,'x.pdf','application/pdf',10)$q$,'42501');
SELECT pg_temp.file_denied($q$SELECT public.remove_task_attachment(pg_temp.f('direct'))$q$,'42501');
RESET ROLE;
SELECT pg_temp.file_login('outsider');
SET LOCAL ROLE authenticated;
SELECT pg_temp.check_file(NOT EXISTS(SELECT 1 FROM public.task_attachments WHERE task_id=pg_temp.f('task')),'Cross-workspace metadata leaked');
SELECT pg_temp.check_file(NOT private.task_file_access(pg_temp.f('workspace')||'/'||pg_temp.f('task')||'/'||pg_temp.f('member')||'/'||pg_temp.f('direct'),false),'Cross-workspace file readable');
SELECT pg_temp.file_denied($q$SELECT public.remove_task_attachment(pg_temp.f('direct'))$q$,'42501');
RESET ROLE;
SELECT pg_temp.file_login('member');
SET LOCAL ROLE authenticated;
SELECT public.begin_task_attachment(pg_temp.f('pending'),pg_temp.f('workspace'),pg_temp.f('task'),NULL,'Pending.txt','text/plain',10);
SELECT pg_temp.file_denied($q$SELECT public.begin_task_attachment(gen_random_uuid(),pg_temp.f('workspace'),pg_temp.f('task'),pg_temp.f('other_comment'),'x.pdf','application/pdf',10)$q$,'42501');
RESET ROLE;
UPDATE public.workspace_members SET role='guest' WHERE workspace_id=pg_temp.f('workspace') AND user_id=pg_temp.f('member');
SET LOCAL ROLE authenticated;
SELECT pg_temp.file_denied($q$SELECT public.finish_task_attachment(pg_temp.f('pending'))$q$,'42501');
SELECT pg_temp.file_denied($q$SELECT public.remove_task_attachment(pg_temp.f('direct'))$q$,'42501');
SELECT public.remove_task_attachment(pg_temp.f('pending'));
RESET ROLE;
UPDATE public.workspace_members SET role='member' WHERE workspace_id=pg_temp.f('workspace') AND user_id=pg_temp.f('member');
UPDATE auth.sessions SET not_after=now()-interval '1 minute' WHERE id=pg_temp.f('member_session');
SET LOCAL ROLE authenticated;
SELECT pg_temp.check_file(NOT EXISTS(SELECT 1 FROM public.task_attachments WHERE task_id=pg_temp.f('task')),'Expired session read metadata');
SELECT pg_temp.file_denied($q$SELECT public.remove_task_attachment(pg_temp.f('direct'))$q$,'42501');
RESET ROLE;
UPDATE auth.sessions SET not_after=NULL WHERE id=pg_temp.f('member_session');
SET LOCAL ROLE authenticated;
SELECT public.remove_task_attachment(pg_temp.f('direct'));
SELECT public.remove_task_attachment(pg_temp.f('direct'));
SELECT pg_temp.file_denied($q$SELECT public.begin_task_attachment(pg_temp.f('direct'),pg_temp.f('workspace'),pg_temp.f('task'),NULL,'Plan.pdf','application/pdf',10)$q$,'23514');
DELETE FROM public.task_comments WHERE id=pg_temp.f('comment');
RESET ROLE;
SELECT pg_temp.check_file(NOT EXISTS(SELECT 1 FROM public.task_attachments WHERE id=pg_temp.f('comment_file')),'Comment deletion retained attachment');
SELECT pg_temp.check_file((SELECT count(*)=3 FROM private.task_file_gc WHERE id IN(pg_temp.f('direct'),pg_temp.f('comment_file'),pg_temp.f('pending'))),'Deletion did not queue every object');
-- Fenced cleanup completion cannot accept a stale worker.
UPDATE private.task_file_gc SET lease_token=gen_random_uuid() WHERE id=pg_temp.f('direct');
SELECT private.finish_task_file_cleanup(pg_temp.f('direct'),gen_random_uuid(),true);
SELECT pg_temp.check_file((SELECT finished_at IS NULL FROM private.task_file_gc WHERE id=pg_temp.f('direct')),'Stale worker completed current lease');
SELECT private.finish_task_file_cleanup(id,lease_token,false) FROM private.task_file_gc WHERE id=pg_temp.f('direct');
SELECT pg_temp.check_file((SELECT lease_token IS NULL AND next_attempt_at>now() FROM private.task_file_gc WHERE id=pg_temp.f('direct')),'Failure was not rescheduled');
UPDATE private.task_file_gc SET lease_token=gen_random_uuid() WHERE id=pg_temp.f('direct');
SELECT private.finish_task_file_cleanup(id,lease_token,true) FROM private.task_file_gc WHERE id=pg_temp.f('direct');
SELECT pg_temp.check_file((SELECT finished_at IS NOT NULL FROM private.task_file_gc WHERE id=pg_temp.f('direct')),'Successful cleanup not completed');
INSERT INTO private.task_file_wakes(token_hash) VALUES(encode(extensions.digest(repeat('a',64),'sha256'),'hex'));
SELECT pg_temp.check_file(private.consume_task_file_wake(repeat('a',64)),'Valid wake rejected');
SELECT pg_temp.check_file(NOT private.consume_task_file_wake(repeat('a',64)),'Replayed wake accepted');
-- Task cascade and abandoned upload cleanup.
SET LOCAL ROLE authenticated;
SELECT public.begin_task_attachment(pg_temp.f('cascade'),pg_temp.f('workspace'),pg_temp.f('other_task'),NULL,'x.txt','text/plain',10);
SELECT public.begin_task_attachment(pg_temp.f('expired'),pg_temp.f('workspace'),pg_temp.f('task'),NULL,'x.txt','text/plain',10);
RESET ROLE;
UPDATE public.task_attachments SET created_at=now()-interval '2 hours' WHERE id=pg_temp.f('expired');
SELECT private.wake_task_file_cleanup();
SELECT pg_temp.check_file(NOT EXISTS(SELECT 1 FROM public.task_attachments WHERE id=pg_temp.f('expired')),'Abandoned upload not expired');
DELETE FROM public.project_tasks WHERE id=pg_temp.f('other_task');
SELECT pg_temp.check_file(NOT EXISTS(SELECT 1 FROM public.task_attachments WHERE id=pg_temp.f('cascade')) AND EXISTS(SELECT 1 FROM private.task_file_gc WHERE id=pg_temp.f('cascade')),'Task cascade did not queue cleanup');
SELECT 'Task file SQL acceptance passed: reservation, replay, validation, role/scope/session isolation, read permissions, comment/task cascades, cleanup leases and one-use authentication' AS result;
ROLLBACK;
